services:
  # 1. FastAPI Gateway Web Service
  - type: web
    name: modularcomponentshowcase-gateway
    env: python
    rootDir: gateway
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: SPRING_BOOT_URL
        value: http://localhost:8000
      - key: MONGO_URL
        value: mongodb+srv://admin:admin@cluster0.omh4o3w.mongodb.net/modular_showcase?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGO_DATABASE
        value: modular_showcase

  # 2. React Frontend Static Site
  - type: web
    name: modularcomponentshowcase
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    plan: free
    routes:
      - type: rewrite
        source: /gateway/*
        destination: https://modularcomponentshowcase-gateway.onrender.com/gateway/*
      - type: rewrite
        source: /*
        destination: /index.html
